version: '3.1'

services:
  cats-vs-dogs:
    networks:
      - mynetwork
    build: ./cats-vs-dogs
    restart: always
    ports:
      - 8080:80
    depends_on:
      - redis
  redis:
    networks:
      - mynetwork
    image: redis
    restart: always
    volumes:
        - redis_data:/data
  frontend:
    networks:
      - mynetwork
    build: ./cats-vs-dogs-frontend
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - cats-vs-dogs
  certbot:
    depends_on: 
      - frontend
    image: certbot/certbot:latest
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot


volumes:
    redis_data: 

networks:
  mynetwork: