version: '3.1'

services:
  frontend:
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./temp.conf:/etc/nginx/conf.d/default.conf
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot
  certbot:
    depends_on: 
      - frontend
    image: certbot/certbot:latest
    volumes:
      - ../data/certbot/conf:/etc/letsencrypt
      - ../data/certbot/www:/var/www/certbot